docs/readme.md

This includes changes in #17 and will close https://github.com/stellar/stellar/issues/131 eventually.
TODO:

Updated docs readme

---

README.md

funny how a much of a difference a newline makes

fix readme instructions formatting

---

lib/operation.js
lib/transaction.js
src/operation.js
src/transaction.js
test/unit/asset_test.js
test/unit/operation_test.js

Fixes #22 
I changed `operationToObject` to take an `operation` object, not `operation._attributes` and updated the code and tests accordingly.
I also fixed some encapsulation violations in `asset_tests`.

Getting rid of encapsulation violations as described in #22

---

src/account.js
src/asset.js
src/memo.js
src/operation.js
src/transaction.js
src/transaction_builder.js
test/unit/account_test.js
test/unit/asset_test.js
test/unit/operation_test.js
test/unit/transaction_test.js

This PR includes:
- Argument checking for most of the functions + tests (close #33, #35),
- Updated jsdocs for `setOptions` (#35),
- `addMemo` helper function and saving memo to a transaction (#37),
- `import`s from files containing classes not index.js.

Arguments checking, helper functions and tests

---

src/keypair.js

Master key dependent on network pass

---

src/memo.js
test/unit/memo_test.js

- Change maximum Memo.text to 28 chars (close #55),
- Add argument checks,
- Add tests.

Changes to Memo and tests

---

src/transaction.js
src/transaction_builder.js
test/unit/transaction_builder_test.js
test/unit/transaction_test.js

Send number of operations multiplied by `BASE_FEE` (100 XLM by [default](https://www.stellar.org/developers/learn/concepts/fees.html)) as a transaction fee.

Update tx fees

---

src/account.js
src/asset.js
src/keypair.js
src/operation.js
src/transaction_builder.js
test/unit/account_test.js
test/unit/keypair_test.js
test/unit/strkey_test.js

To implement: https://github.com/stellar/horizon/issues/214
Close https://github.com/stellar/js-stellar-base/issues/63

Replace Address with Account ID

---

src/account.js
src/transaction_builder.js
test/unit/account_test.js
test/unit/transaction_builder_test.js
test/unit/transaction_test.js

SequenceNumber values (uint64) can be too big for JS numbers. This is breaking change and will be release in a next minor release.

Use BigNumber for sequence numbers

---

src/operation.js

add comment about AUTH_IMMUTABLE_FLAG

---

README.md

Related issues:
https://github.com/stellar/js-stellar-base/issues/20
https://github.com/stellar/stellar-protocol/issues/30

add information about cdnjs to README

---

src/generated/stellar-xdr_generated.js
src/operation.js
test/unit/operation_test.js
xdr/Stellar-ledger-entries.x
xdr/Stellar-ledger.x
xdr/Stellar-transaction.x

Close https://github.com/stellar/js-stellar-base/issues/77

ManageData operation support

---

src/operation.js

The current description of the price is actually misleading.

Update offer operations price doc

---

src/asset.js
src/base58.js
src/operation.js
src/signing.js
src/strkey.js
src/util/checksum.js

General refactor to resolve issues according to code climate. Took most of the low hanging fruit.
**Before** (*35 issues and maintainability D*): https://codeclimate.com/github/stellar/js-stellar-base/issues
**After** (*17 issues and maintainability C*): https://codeclimate.com/github/robertDurst/js-stellar-base/issues 
Significant changes:
* Moved duplicated `verifyChecksum` to own file within `util/checksum`
* Split `checkFastSigning` into 3 functions
* Removed two unused lodash imports
* Utilized `switch(true)` instead of numerous if-else statements. According to code climate, this improves the Cognitive Complexity: https://docs.codeclimate.com/docs/cognitive-complexity
Please let me know if anything is stylistically unkosher!

Code climate refactors

---

src/signing.js

Missed a couple here.
Ref #132

Finish Buffer dep fix for node 10

---

src/operation.js
test/unit/operation_test.js

Close https://github.com/stellar/js-stellar-sdk/issues/204

Fix decoding empty homeDomain

---

.prettierignore
docs/reference/base-examples.md
docs/reference/building-transactions.md
src/transaction.js
src/transaction_builder.js

(1) Add `setTimeout` to `TransactionBuilder` code examples (fixes https://github.com/stellar/js-stellar-sdk/issues/229)
(2) Add warning about transactions incrementing sequence numbers (fixes https://github.com/stellar/js-stellar-sdk/issues/207)
(3) Make `setTimeout` docs clearer (fixes #155)

Docs improvements

---

CHANGELOG.md
docs/reference/base-examples.md
src/transaction_builder.js

- Fix transaction example (courtesy of https://github.com/stellar/js-stellar-base/pull/138)
- Fix new account example (courtesy of https://github.com/stellar/js-stellar-base/pull/121)

Documentation fixes suggested by the community

---

types/index.d.ts

Adds types for the new methods introduced by #161.

Add types for Transaction.{addSignature,getKeypairSignature}

---

src/transaction.js
test/unit/transaction_test.js

This PR will add code to verify a signature when added to a transaction.
This is valuable for scenarios where a party receives a signature from another party and wants to add this signature to a transaction. The first party needs to make sure that the signature from the other party is valid.
This will become apparent once the transaction is submitted to horizon – it will fail if the signature is invalid. However, for smart contract schemes (say, payment channels) this will usually happen much later.

Also verify signature when adding to transaction

---

src/generated/stellar-xdr_generated.js
xdr/Stellar-overlay.x
xdr/Stellar-transaction.x

See [stellar core xdr](https://github.com/stellar/stellar-core/blob/29d4b1a16289161822251dd91d589ebe943b3f46/src/xdr/Stellar-overlay.x#L131)

xdr SCP_MESSAGE wrong type.

---

types/index.d.ts

Fix types: Fee is no longer optional

---

types/index.d.ts

Fix typings for Transaction Sequence Number

---

types/index.d.ts

Fix typings for Account Sequence Number

---

src/strkey.ts
src/util/checksum.ts

Typings for strkey and checksum

---

src/@types/xdr.ts
src/memo.ts

refs #188 
I got confused initially thinking this was the typings for js-xdr, but it is actually for the autogenerated xdr code.

Fix XDR namespace

---

src/signing.ts

refs #188 
Add typings for signing.

Typings for signing

---

src/@types/operation.ts
src/operation.ts
src/operations/index.ts

Add typings for pathPayment.

---

src/keypair.ts

fix(typescript): keypair

---

src/transaction.ts

fix(typescript): transaction

---

src/operation.ts
src/operations/index.ts

Ref #188
`src/operations/index.ts` is done, except for
- missing types from `js-xdr`
- many `any` around

fix(typescript): BaseOperation

---

src/keypair.js
src/transaction.js

Fix no-network warning messages according to #207.

Fix no-network warnings

---

src/transaction.js
test/unit/transaction_test.js

Throw error on invalid network passphrases

---

gulpfile.js
package.json
webpack.config.common.js

See https://github.com/stellar/js-stellar-wallets/pull/132 for the conversation around the issue and solution.

Compile a commonjs-module along with the browser.js

---

yarn.lock

Updates multiple dependencies and fixes a couple of security alerts.

Yarn upgrade.

---

package.json

This is working with each node engine so remove the restriction.

Remove node engine restriction

---

docs/reference/base-examples.md
src/asset.js
src/memo.js
src/operation.js
src/operations/create_account.js

Fix doc link

---

src/network.js

Fixes https://github.com/stellar/js-stellar-sdk/issues/415

Use console.trace to get line num in Networks.use

---

types/index.d.ts

This is for issue #309 
I changed the option of ManageData operation to set value to null.

Change option of ManageData operation to set value to null

---

src/transaction_builder.js
test/unit/fee_bump_transation_test.js
test/unit/transaction_builder_test.js
test/unit/transaction_test.js

Fixes https://github.com/stellar/js-stellar-base/issues/354

Generate V1 transactions and allow V0 transactions to be fee bumped

---

src/transaction_builder.js

feeSource is type Keypair

---

CHANGELOG.md
Gemfile.lock
src/generated/stellar-xdr_generated.js
src/operations/allow_trust.js
test/unit/operation_test.js
types/xdr.d.ts
xdr/Stellar-ledger-entries.x
xdr/Stellar-transaction.x

Additionally, update the Gemfile to use [xdrgen v0.1.0](https://github.com/stellar/xdrgen/commit/ba75f1615f99f5d4b176536bf83889b854de5b51) which includes some [crucial bug-fixes](stellar/xdrgen#52) from the Protocol 15 days. Closes #393.

Update XDR to include CAP-35 definitions

---

CHANGELOG.md
package.json

Should be rebased first, after #399 gets merged.

Release v5.0.0 of the SDK.

---

CONTRIBUTING.md

This enumerates a release checklist for posterity. Should merge alongside stellar/js-stellar-sdk#631 so cross-references work.

Describe release process in CONTRIBUTING.md.

---

CHANGELOG.md
package.json

I'd like to get this in before any dependabot stuff to ensure a stable version.

Release v5.3.1

---

docs/readme.md
docs/reference/base-examples.md
docs/reference/building-transactions.md
src/asset.js
src/liquidity_pool_asset.js
src/liquidity_pool_id.js
src/memo.js
src/operation.js
src/operations/create_account.js
src/operations/set_options.js
src/transaction_builder.js

Part of https://github.com/stellar/java-stellar-sdk/issues/340

Updating old docs url to new docs urls

---

CHANGELOG.md
types/index.d.ts

Adds `Buffer` as type option for public/secret key parameter in the `Keypair` constructor

---

.github/workflows/tests.yml
README.md

Update README with minimum Node version

---

src/generated/stellar-xdr_generated.js
src/transaction.js
src/transaction_builder.js
test/unit/fee_bump_transation_test.js
test/unit/transaction_builder_test.js
types/xdr.d.ts
xdr/Stellar-ledger-entries.x
xdr/Stellar-ledger.x
xdr/Stellar-overlay.x
xdr/Stellar-transaction.x
xdr/Stellar-types.x

This is a **bare-minimum** set of code updates to work with the Protocol 19 XDR. That means there is no new functionality introduced, particularly around the new transaction preconditions in [CAP-21](https://stellar.org/protocol/cap-21). A robust refactor to this will come in a separate PR.
The purpose of this PR is to have a shared, working ground to work on the disjoint tasks outlined in stellar/js-stellar-sdk#763.

Update XDR definitions and relevant code for Protocol 19

---

.github/workflows/npm_publish.yml
CHANGELOG.md
package.json

**This release adds support for Protocol 19**, which includes [CAP-21](https://stellar.org/protocol/cap-21) (new transaction preconditions) and [CAP-40](https://stellar.org/protocol/cap-40) (signed payload signers).

Release v8.0.0-beta.0

---

src/transaction_builder.js
test/unit/transaction_test.js

Please check the test case for more information.

fix: fixed `TransactionBuilder.build()` to set correct `minAccountSequence`

---

CHANGELOG.md
package.json

This release includes a bugfix, an XDR update, and a small addition.
You can refer to the CHANGELOG.md for details.

Release v8.1.0

---

package.json
src/network.js
types/index.d.ts

as per https://github.com/stellar/ops/issues/1832

Add futurenet passphrase for soroban.

---

CHANGELOG.md
package.json

Release v8.2.1.

---

package.json
src/generated/next_generated.js
types/next.d.ts
xdr/next/Stellar-contract-spec.x
xdr/next/Stellar-contract.x

To include: https://github.com/stellar/stellar-xdr/commit/dc23adf60e095a6ce626b2b09128e58a5eae0cd0

Update soroban xdr

---

src/address.js
test/unit/address_test.js

Minor helper that would have been useful just now.

Add Address.toBuffer method

---

CHANGELOG.md
package.json
test/unit/asset_test.js
yarn.lock

It's all developer dependencies, upgraded via a direct `yarn upgrade-interactive --latest`.

Bump all dependencies to their latest versions.

---

package.json

This will let soroban-client include this new library, which will fix system-test on this PR: https://github.com/stellar/soroban-tools/pull/668

Release v9.0.0-soroban.2

---

package.json
yarn.lock

Release `v10.0.0-soroban.2`

---

.github/workflows/bundle_size.yml
.github/workflows/tests.yml

Related: https://github.com/stellar/js-stellar-base/issues/643

Trying out a GitHub Action that compares before-and-after bundle sizes.

---

Makefile
config/prettier.config.js
src/generated/curr_generated.js
src/generated/next_generated.js
types/curr.d.ts
types/next.d.ts
xdr/next/Stellar-contract-config-setting.x

This upgrades XDR in line with stellar/go#5013.

WIP: Yet another XDR refresh

---

types/index.d.ts

**Summary:**
- add soroban class types to `index.d.ts`

add soroban class types to index.d.ts

---

CHANGELOG.md
package.json

This release includes:
* https://github.com/stellar/js-stellar-base/pull/718

Release v10.0.1 which includes a bugfix.

---

CHANGELOG.md
package.json
yarn.lock

This release just includes Protocol 21 XDR and dependency upgrades.

Release v11.1.0

---

types/index.d.ts

Addresses https://github.com/stellar/js-stellar-base/issues/750

Add isValidContract type to the StrKey class

---

CHANGELOG.md
package.json
yarn.lock

This release includes two new features and a bugfix:
* #794 
* #783

Prepare v13.1.0 for release
