package.json

This should fix the warnings when installing something:
```
npm WARN package.json js-stellar-lib@0.0.7 No repository field.
```

add repository field in package.json

---

src/network.js
test/unit/network_test.js

This PR changes default network to testnet. Reasoning:
* Testnet is, in most cases, the first network developers are interacting with,
* With default Public Network developers can send real funds by accident. They should explicitly state they want to use Public Network (by calling `usePublicNet()`).

Change default network to testnet

---

src/network.js
test/unit/network_test.js

This PR:
* Changes `usePublicNet` to `usePublicNetwork`,
* Changes `useTestNet` to `useTestNetwork`,
* Depreciates previous methods: `usePublicNet`, `useTestNet`.

Change Network methods names

---

src/operation.js
src/util/continued_fraction.js
test/unit/util/continued_fraction_test.js

Throw `Error` in `best_r` when the best rational approximation cannot be found. Operations that contain such approximations would be [rejected](https://github.com/stellar/stellar-core/blob/eed89649c2060b8e9dacffe2cec4e8b258b32416/src/transactions/ManageOfferOpFrame.cpp#L390) by stellar-core anyway so it's better to reject them early.

Throw Error when the best rational approximation cannot be found

---

src/operation.js
test/unit/operation_test.js

The PR allows the price to be an object with numerator and denominator in Operation.managerOffer and Operation.createPassiveOffer. Otherwise, precision is lost, for instance, `1000` becomes `999.99999`.

price fraction in Operation.managerOffer and Operation.createPassiveOffer

---

src/transaction_builder.js
test/unit/transaction_test.js

The way the base sdk checks for a submitted fee rules 0 out. Since having 0 as transaction fee is actually fine in the core config, I see no reason why it can't be set in this SDK.
I've also taken the liberty of adding a test for this, but I'm not sure if this is the right way to implement this test or not. 
If this pull request fails to meet any of the contributing requirements, please let me know and I will fix them.

Make 0 a valid number for transaction fee

---

docs/learn/base-examples.md

The comment of this code block has a small typo. This should fix it.

Small typo in the comment

---

src/index.js
src/operation.js
test/unit/operation_test.js

Adds and exports the account flags so `Operation.setOptions` can be used like this now:
```js
StellarBase.Operation.setOptions({
setFlags: StellarBase.AuthRevocableFlag | StellarBase.AuthImmutableFlag
});
```
Close https://github.com/stellar/js-stellar-base/issues/87

Export account flags constants

---

README.md
package.json
src/index.js
src/signing.js

Move `ed25519` to `optionalDependencies` and fallback to `tweetnacl` if `ed25519` installation failed. Confirmed working as expected in the clean (git, node, npm, no compilation tools) Windows virtual machine.
Developers can check if native Ed25519 package is used by examining `StellarBase.fastSigning` variable.
This is a breaking change and will be published in `0.6.0`.
Close #68.

Optional ed25519

---

docs/readme.md

Pointed "Building Transactions" and "Examples" to their correct pages

Link update

---

src/keypair.js
src/network.js
src/transaction.js
src/transaction_builder.js
test/unit/network_test.js
test/unit/strkey_test.js
test/unit/transaction_test.js

Some users forget to switch to public network (by executing `Network.usePublicNetwork()`) before deploying apps because right now test network is a default choice, selected automatically. This PR changes `Network` module to not select a default network.
Merging into `0.7.0` branch because it's a breaking change.

No default network

---

.travis.yml
CHANGELOG.md
package.json
src/account.js
src/asset.js
src/generated/stellar-xdr_generated.js
src/index.js
src/keypair.js
src/network.js
src/operation.js
src/strkey.js
src/transaction.js
src/transaction_builder.js
test/unit/keypair_test.js
test/unit/network_test.js
test/unit/operation_test.js
test/unit/strkey_test.js
test/unit/transaction_test.js
xdr/Stellar-ledger-entries.x
xdr/Stellar-ledger.x
xdr/Stellar-transaction.x
xdr/Stellar-types.x

* Support for new signer types: `sha256Hash`, `preAuthTx`.
* `StrKey` helper class with `strkey` encoding related methods.
* Removed deprecated methods: `Keypair.isValidPublicKey` (use `StrKey`), `Keypair.isValidSecretKey` (use `StrKey`), `Keypair.fromSeed`, `Keypair.seed`, `Keypair.rawSeed`.
* **Breaking changes**:
* `Network` must be explicitly selected. Previously testnet was a default network.
* `Operation.setOptions()` method `signer` param changed.
* `Keypair.fromAccountId()` renamed to `Keypair.fromPublicKey()`.
* `Keypair.accountId()` renamed to `Keypair.publicKey()`.
* Dropping support for `End-of-Life` node versions.

Version 0.7.0

---

src/keypair.js
test/unit/keypair_test.js

In https://github.com/stellar/js-stellar-base/issues/101 @pakokrew noticed that `Keypair.constructor` usage is not clear. I realized that this class can be further improved (see https://github.com/stellar/js-stellar-base/pull/96).
* `Keypair.constructor` now requires `type` field to define public-key signature system used in this instance (so `Keypair` can support other systems in a future). It also checks if public key and secret key match if both are passed (to prevent nasty bugs).
* `Keypair.fromRawSeed` has been renamed to `Keypair.fromRawEd25519Seed` to make it clear that the seed must be Ed25519 seed.

Improve Keypair class

---

src/asset.js
src/index.js
src/memo.js
src/operation.js
src/transaction.js
src/transaction_builder.js
test/unit/asset_test.js
test/unit/memo_test.js
test/unit/operation_test.js
test/unit/transaction_test.js

This PR makes it possible to instantiate `Memo` class so it's easier to check it's type and value (without dealing with low level `xdr.Memo` objects).
Also changed `Asset.toXdrObject` to `Asset.toXDRObject` and `Operation.operationToObject` to `Operation.toXDRObject` for consistency.
Close https://github.com/stellar/js-stellar-base/issues/100

Memo instance

---

src/account.js

Was confused by the docs where “Account tracts the sequential number”. I suspect it should be “tracks”.

Docs: Account: typo (minor)

---

package.json

Make webpack & friends ignore the `ed25519` package, so you don't need the `IgnorePlugin` in the application's webpack config. The `stellar-base` package knows best what dependencies it has and how they work, so it should do the ignoring 😉

Add `browser` prop to package.json

---

.travis.yml
src/base58.js
src/keypair.js
src/memo.js
src/operation.js
src/signing.js
src/strkey.js
src/transaction.js
test/unit/asset_test.js
test/unit/hashing_test.js
test/unit/keypair_test.js
test/unit/memo_test.js
test/unit/operation_test.js
test/unit/signing_test.js

As of node v10, `new Buffer` is deprecated.
They recommend we replace it with one of the following:
* Buffer.from(str, encoding="utf8")
* Buffer.alloc(number, fill)
* Buffer.allocUnsafe()
Here is what node.js says:
> Drop support for Node.js ≤ 4.4.x and 5.0.0 — 5.9.x
> This is the recommended solution nowadays that would imply only minimal overhead.
> 
> The Node.js 5.x release line has been unsupported since July 2016, and the Node.js 4.x release line reaches its End of Life in April 2018 (→ Schedule). This means that these versions of Node.js will not receive any updates, even in case of security issues, so using these release lines should be avoided, if at all possible.
> 
> What you would do in this case is to convert all new Buffer() or Buffer() calls to use Buffer.alloc() or …

Fix Buffer for node v10 deprecation

---

src/operation.js
test/unit/operation_test.js
test/unit/transaction_test.js

This PR changes `Operations._fromXDRAmount` to not use scientific notation (`1e-7`) for small amounts like `0.0000001`.

Operations._fromXDRAmount fix

---

CHANGELOG.md
docs/reference/base-examples.md
docs/reference/building-transactions.md
src/index.js
src/transaction_builder.js
test/unit/operation_test.js
test/unit/transaction_builder_test.js
test/unit/transaction_test.js

If a user calls `TransactionBuilder` without a fee, issue a console log. Also update code examples to provide a fee, and export BASE_FEE. Part of #166.

Warn about non-explicit transaction fees

---

README.md
gulpfile.js
package.json
src/keypair.js
src/signing.js

I just now realized I opened up the issue in the wrong repo,
https://github.com/stellar/js-stellar-sdk/issues/242
This PR replaces the `ed25519` package with `sodium-native` when running node, making transaction signing almost twice as fast. It also makes the necessary changes so that key generation is done natively, if possible, for a similar speedup.

Replace ed25519 with libsodium/sodium-native

---

CHANGELOG.md
Gemfile
Gemfile.lock
src/generated/stellar-xdr_generated.js
src/operation.js
src/operations/create_passive_sell_offer.js
src/operations/index.js
src/operations/manage_buy_offer.js
src/operations/manage_sell_offer.js
test/unit/operation_test.js
types/index.d.ts
xdr/Stellar-ledger-entries.x
xdr/Stellar-ledger.x
xdr/Stellar-transaction.x
yarn.lock

Stellar Protocol 11 Compatibility

---

CHANGELOG.md
src/transaction_builder.js
test/unit/transaction_test.js

If someone tries to build a transaction without providing the base fee, throw an error. Closes #166.

Deprecate base fee with error

---

src/operation.js
src/operations/index.js
test/unit/operation_test.js

Restore deprecated operations Operation.createPassiveOffer and Operation.manageOffer. When called, make them console.log an error, and return the correct new offer name. Fixes #190.

Restore deprecated functions

---

package.json

The latest version broke our React storybook build with `Module not found: Error: Can't resolve 'fs'`. This is the fix. Was probably just forgotten when `ed25519` was replaced by `sodium-native`.

Fix package.json `browser` build

---

src/asset.js
test/unit/asset_test.js

Hi there! 👋 
What about overriding `Asset.toString()` method? I believe it would be useful to return something more meaningful from that. I ended up with `code-issuer` format and just `native` for lumens.
What do you think?
P.S. Sorry for the formating mess in a diff, it's prettier in the pre-commit hook 😕

Add `toString()` to Asset

---

types/index.d.ts
types/test.ts

We didn't update the typings in #207 which caused #237.

Add types for new networkPassphrase argument. Fix #237.

---

src/base58.ts
src/util/checksum.ts

fix(typescript): base58

---

gulpfile.js
package.json
yarn.lock

We need this since it updates the plugin to drop a dependency which is not longer maintained.

Use fork for deprecated gulp-coveralls.

---

src/@types/xdr.d.ts
src/asset.ts
src/generated/stellar-xdr_generated.d.ts
src/keypair.ts
src/memo.ts
src/operation.ts
src/operations/index.ts
src/strkey.ts
src/transaction.ts
src/transaction_builder.ts

Ref #188
Summary:
- I'm struggling to type xdr definitions without experience with them
- "accidentally" typed a lot of `js-xdr` library along the way
- overall far from done, but LGTM to merge - it's better than before
RFC:
- the only place where code, not types, were touched is at 117cd16 . That should not change behavior, but I may have missed something.
TODO:
- more types
- Can someone who understands what's going on at xdr help to type them?
- Perhaps `js-xdr` types should be moved upstream?
- At many places there's type mismatch, plain `number` where Int32 is expected, or `string` for Opaque, etc. Is that expected? Should we leave it like that?

fix(typescript): xdr - add plenty of types

---

types/index.d.ts

This is required for deserializing the native asset, e.g., when parsing the value `JSON.stringify(Asset.native())` and handing the result to the `Asset` constructor.
The javascript is perfectly able to handle this case anyway.

Allow `undefined` issuer for `Asset` constructor.

---

CHANGELOG.md
src/generated/stellar-xdr_generated.js
src/operation.js
src/operations/index.js
src/operations/path_payment.js
src/operations/path_payment_strict_receive.js
src/operations/path_payment_strict_send.js
test/unit/operation_test.js
types/index.d.ts
xdr/Stellar-transaction.x

Add support for [stellar-core protocol 12 release](https://github.com/stellar/stellar-core/projects/11) and [CAP 24](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0024.md) ("Make PathPayment Symmetrical").
- `Operation.pathPaymentStrictSend`: Sends a path payment, debiting from the source account exactly a specified amount of one asset, crediting at least a given amount of another asset. 
The following operation will debit exactly 10 USD from the source account, crediting at least 9.2 EUR in the destination account 💸:
```js
var sendAsset = new StellarBase.Asset(
'USD',
'GDGU5OAPHNPU5UCLE5RDJHG7PXZFQYWKCFOEXSXNMR6KRQRI5T6XXCD7'
);
var sendAmount = '10';
var destination =
'GCEZWKCA5VLDNRLN3RPRJMRZOX3Z6G5CHCGSNFHEYVXM3XOJMDS674JZ';
var destAsset = new StellarBase.Asset( …
```

Support stellar-core protocol 12 

---

src/generated/stellar-xdr_generated.js
xdr/Stellar-ledger.x
xdr/Stellar-overlay.x

Regenerate the XDR definitions to include [MetaV2](https://github.com/jonjove/stellar-core/blob/b299b3a458a15f592352c67d4da69baa6e8fbb6a/src/xdr/Stellar-ledger.x#L309) support (also see [#1902](https://github.com/stellar/go/issues/1902)).

Regenerate the XDR definitions to include MetaV2

---

docs/reference/base-examples.md

Related to https://github.com/stellar/docs/issues/431 I think the `.setTimeout()` was missed in this example.

Update creating an account example

---

src/transaction_builder.js
test/unit/transaction_builder_test.js

Fix `Cannot read property 'toString' of undefined` error. Did occur when either `timebounds.minTime` or `timebounds.maxTime` were set, but not both.
PS: Need to test this fix some more.

Fix crash on partially defined time bounds

---

src/transaction_builder.js
test/unit/transaction_builder_test.js

There were multiple issues around timebounds logic like setting `TimeoutInfinite` or trying to pass partially defined timebounds (which is not valid), there were some validations for this but the code was buggy.
This PR:
- Fixes timebounds validation, making sure that both `minTime` and `maxTime` are defined.
- Fixes `setTimeout(TimeoutInfinite)` - this was broken.
This fixes #312 and is related with #303

Fix multiple timebounds related bugs.

---

src/generated/stellar-xdr_generated.js
src/operations/allow_trust.js
src/transaction.js
src/transaction_builder.js
test/unit/operation_test.js
test/unit/transaction_envelope_test.js
test/unit/transaction_test.js
types/index.d.ts
xdr/Stellar-ledger-entries.x
xdr/Stellar-transaction.x

Add protocol 13 support with backwards compatibility support for protocol 12.
In order to provide a seamless transition between protocol 12 and 13, we need to release a new version of the SDK that can read  and generate transactions which will work in both protocols.
This pull request:
- Updates the XDR definitions with protocol 13.
- Extends `Transaction` to work with `TransactionV1Envelope` and `TransactionV0Envelope`.
- Generates `TransactionEnvelope` which can be read by protocol 12 or protocol 13.
- Reads `TransactionEnvelope` generated by protocol 12 or protocol 13.
- Adds backward compatibility support for [CAP0018](https://github.com/stellar/stellar-protocol/blob/f01c9354aaab1e8ca97a25cf888829749cadf36a/core/cap-0018.md)
- Adds partial support for …

Protocol 13 support

---

src/generated/stellar-xdr_generated.js
src/keypair.js
src/operation.js
src/operations/account_merge.js
src/operations/path_payment_strict_receive.js
src/operations/path_payment_strict_send.js
src/operations/payment.js
src/transaction_builder.js
test/unit/keypair_test.js
xdr/Stellar-ledger.x
xdr/Stellar-overlay.x
xdr/Stellar-transaction.x
xdr/Stellar-types.x

Add support for CAP0027.
Protocol 13 introduces multiplexed accounts, replacing some fields with the union `xdr.MuxedAccount` where `xdr.PublicKey` was previously used.
This pull requests:
- Extends `Keypair` with a new method `.xdrMuxedAccount` which creates a new `MuxedAccount` using the `ed25519` discriminant.
- Updates all the operations which changed their attribute from `PublicKey` to `MuxedAccount`.
Fixes #324 
This update doesn't include breaking changes for users of this library. However, if you are relying on XDRs, you'll get now a `MuxedAccount` where a `PublicKey` was returned. 
As long as you are not checking for the instance type, your code should continue to work since both `MuxedAccount` and `PublicKey` have the discriminant `ed25519` which returns the same data type. 
- …

Add support for CAP 0027 (MuxedAccounts)

---

src/strkey.js
test/unit/strkey_test.js

Add support for SEP0023.
CAP-0027 introduced  multiplexed addresses, this introduces a new strkey format to represent both the public key and 64-bit ID of a MuxedAccount.
Fix #325

Add SEP 0023 support.

---

src/fee_bump_transaction.js
src/generated/stellar-xdr_generated.js
src/index.js
src/transaction.js
src/transaction_base.js
src/transaction_builder.js
test/unit/fee_bump_transation_test.js
test/unit/operation_test.js
test/unit/transaction_builder_test.js
test/unit/transaction_test.js
types/index.d.ts
types/test.ts
xdr/Stellar-transaction.x

Add the class `FeeBumpTransaction` to represent fee bump transactions.
This pull request updates some of the code introduced in #321,  creating a different class to represent fee bump transaction.
While having a single class could work, long term, having different classes to separate both type of transactions is less error prone and makes the interface on fee bump transactions more explicit.
When you create a new `FeeBumpTransaction` you can reach the inner transaction via `.innerTransaction`, this returns an instance of `Transaction` which gives access to all the properties on the inner transaction, like the original fee, sourceAccount, operations, and memo.

Add FeeBumpTransaction class

---

src/fee_bump_transaction.js
src/strkey.js
src/transaction.js
src/transaction_base.js
test/unit/fee_bump_transation_test.js
test/unit/strkey_test.js
test/unit/transaction_test.js

The initial implementation was not compatible with an `xdr.MuxedAccount` but rather the `muxedEd25119` discriminant. 
This PR:
- Extends `encodeMuxedAccount` to handle the raw data for `xdr.MuxedAccount`, it can return a `G..` or `M...` account.
- Extends `decodeMuxedAccount` to handle `G..` or `M..` accounts, the result can be used to create a valid `xdr.MuxedAccount`.

Extend StrKey to handle xdr.MuxedAccount

---

src/operation.js
src/operations/account_merge.js
src/operations/path_payment_strict_receive.js
src/operations/path_payment_strict_send.js
src/operations/payment.js
test/unit/operation_test.js

Extend the operations builder to take muxed accounts. 
Example:
```js
var opts = {};
opts.destination = 'MAAAAAAAAAAAAAB7BQ2L7E5NBWMXDUCMZSIPOBKRDSBYVLMXGSSKF6YNPIB7Y77ITLVL6';
opts.source = 'MAAAAAAAAAAAAAB7BQ2L7E5NBWMXDUCMZSIPOBKRDSBYVLMXGSSKF6YNPIB7Y77ITLVL6';
let op = StellarBase.Operation.accountMerge(opts);
```

Support operations with muxed accounts.

---

src/transaction_base.js

The previous syntax was not valid, which producing an invalid link. With this we'll get the right links relative to the children inheriting this class.
Also the bad URL was breaking the developers portal build.

Fix URLs to functions in TransactionBase.

---

CHANGELOG.md
src/fee_bump_transaction.js
src/operation.js
src/operations/account_merge.js
src/operations/path_payment_strict_receive.js
src/operations/path_payment_strict_send.js
src/operations/payment.js
src/strkey.js
src/transaction.js
src/util/decode_encode_address.js
src/util/decode_encode_muxed_account.js
test/unit/fee_bump_transation_test.js
test/unit/operation_test.js
test/unit/strkey_test.js
test/unit/transaction_test.js
types/index.d.ts

Remove SEP23 (Muxed Account StrKeys) support until SEP23 moves from a `draft` to `accepted`. 
Fix #348

Rollback SEP23 (Muxed Account strkeys) support.

---

CHANGELOG.md
src/operations/allow_trust.js
types/index.d.ts

I forgot to include proper documentation for this functionality. This PR update the TypeScript types for better linting, update the `jsdocs`, and the changelog.
Fix #557.

Document new authorize to maintain liabilities functionality.

---

CHANGELOG.md
src/claimant.js
src/index.js
test/unit/claimant_test.js
types/index.d.ts
types/test.ts

Add a new helper class to make it easier to create `xdr.Claimant` which will be used  to create and read the `CreateClaimableBalance` operations. 
By default it will create a claimant with an unconditional predicate if none is passed:
```
const claimant = new StellarBase.Claimant(
'GCEZWKCA5VLDNRLN3RPRJMRZOX3Z6G5CHCGSNFHEYVXM3XOJMDS674JZ'
);
```
But additionally, it offers some helpers to make it easier to build new claim predicates:
```
Claimant.predicateUnconditional();
Claimant.predicateAnd(left, right);
Claimant.predicateOr(left, right);
Claimant.predicateNot(predicate);
Claimant.predicateBeforeAbsoluteTime(unixEpoch);
Claimant.predicateBeforeRelativeTime(seconds);
```
The helpers above will appear in the documentation. The following is a simple snippet showing how to create a …

Add Claimant class wrapper.

---

CHANGELOG.md
src/operation.js
src/operations/claim_claimable_balance.js
src/operations/create_claimable_balance.js
src/operations/index.js
test/unit/operation_test.js
types/index.d.ts
types/test.ts

Extend the `Operation` class with two new helpers which allow the creation of CAP23 related operations:
- Add `Operation.createClaimableBalance`.
Extend the operation class with a new helper to create claimable balance operations.
```js
const asset = new Asset(
'USD',
'GDGU5OAPHNPU5UCLE5RDJHG7PXZFQYWKCFOEXSXNMR6KRQRI5T6XXCD7'
);
const amount = '100.0000000';
const claimants = [
new Claimant(
'GCEZWKCA5VLDNRLN3RPRJMRZOX3Z6G5CHCGSNFHEYVXM3XOJMDS674JZ',
Claimant.predicateBeforeAbsoluteTime("4102444800000")
)
];
const op = Operation.createClaimableBalance({
asset,
amount,
claimants
});
```
- Add `Operation.claimClaimableBalance`.
Extend the operation class with a new helper to create claim claimable balance operations. It receives the `balanceId` as exposed by Horizon in the …

Add helpers to create CAP23 operations.

---

CHANGELOG.md
src/operation.js
src/operations/begin_sponsoring_future_reserves.js
src/operations/end_sponsoring_future_reserves.js
src/operations/index.js
src/operations/revoke_sponsorship.js
test/unit/operation_test.js
types/index.d.ts
types/test.ts
types/xdr.d.ts

Extend the operation class with helpers that allow sponsoring reserves and also revoke sponsorships.
To start sponsoring reserves for an account use:
- `Operation.beginSponsoringFutureReserves`
- `Operation.endSponsoringFutureReserves`
To revoke a sponsorship after it has been created use any of the following helpers:
- `Operation.revokeAccountSponsorship`
- `Operation.revokeTrustlineSponsorship`
- `Operation.revokeOfferSponsorship`
- `Operation.revokeDataSponsorship`
- `Operation.revokeClaimableBalanceSponsorship`
- `Operation.revokeSignerSponsorship`
The following example contains a transaction which sponsors operations for an account and then revoke some sponsorships.
```js
const transaction = new StellarSdk.TransactionBuilder(account, {
fee: "100",
networkPassphrase: …
```

Add support for Sponsored Reserves (CAP33).

---

src/operations/create_account.js
test/unit/operation_test.js

Allow account create operation with zero balance.

---

test/unit/crypto_test.js
types/test.ts

From what I can gather, this linting error is due to the fact that `MemoValue` is [not expanded](https://github.com/Microsoft/dtslint/issues/57#issuecomment-451666294) into its constituent types (`string | Buffer | null`, from index.d.ts:106) by the linter. It's not an actual error, obviously, since the passed parameter is a string. 
Since there's no resolution aside from the [issue being resolved](https://github.com/Microsoft/dtslint/issues/57#issuecomment-451666294), it doesn't make sense to perpetually allow CI to false-positive every PR because of it.

Stop linting MemoValue incorrectly so CI passes

---

CHANGELOG.md
src/operations/claim_claimable_balance.js
test/unit/operation_test.js

Enforce claimable balance IDs to be 72-byte strings.

---

src/claimant.js

In response to stellar/new-docs#345.

Clarify units on absolute predicates in the documentation.

---

CHANGELOG.md
README.md
src/generated/stellar-xdr_generated.js
src/operation.js
src/operations/allow_trust.js
src/operations/claim_claimable_balance.js
src/operations/clawback.js
src/operations/clawback_claimable_balance.js
src/operations/create_claimable_balance.js
src/operations/index.js
src/operations/set_trustline_flags.js
test/unit/operation_test.js
types/index.d.ts
types/xdr.d.ts
xdr/Stellar-transaction.x

Fulfills creation the [list of CAP-35 features](https://gist.github.com/2opremio/89c4775104635382d51b6f5e41cbf6d5#new-operations):
- `clawback` with the following fields:
- Asset fields (identical to the asset fields in the Change Trust, Allow Trust and Set Trustline Flags operations)
- `asset_type`
- `asset_code`
- `asset_issuer`
- `from` - account from which the asset is clawed back
- `amount` - asset amount clawed back
- `clawback_claimable_balance`, with the following field:
- `balance_id` - claimable balance identifer of the claimable balance to be clawed back
- `set_trust_line_flags`, with the following fields:
- Asset fields (identical to the asset fields in the Change Trust, Allow Trust and Set Trustline Flags operations)
- `asset_type`
- `asset_code`
- `asset_issuer`
- `trustor` …

Add CAP-35 support to the SDK.

---

README.md

Basically, replace `npm` with the `yarn` equivalent in the instructions, and give more details on how to update the auto-generated XDR files.
(There's also some minor whitespace changes but those are irrelevant.)

Update README with more details on XDR generating & installation instructions.

---

CHANGELOG.md
src/operation.js
src/operations/set_trustline_flags.js
types/index.d.ts
types/test.ts

This builds on @overcat's work in #406 (you can see the [branch diff here](https://github.com/overcat/js-stellar-base/compare/dev-types-cap35...stellar:cap35-hints)), introducing test cases for the type hints and allows certain flags to be left off.

Add Typescript definitions for CAP-35 operations.

---

src/index.js
src/operation.js
src/operations/set_options.js
test/unit/operation_test.js
types/index.d.ts
types/test.ts

This should allow library consumers to do things like:
```js
const op = StellarSdk.Operation.setOptions({ 
setFlags: StellarSdk.AuthFlag.clawbackEnabled,
});
```

Expose the AuthClawbackEnabled flag for use with the SetOptionsOp

---

CHANGELOG.md
types/index.d.ts
types/test.ts

The SDK uses the full name (i.e. `AuthClawbackEnabledFlag`) rather than going through the namespace (e.g. `AuthFlag.clawbackEnabled`), and the Typescript files have been updated accordingly to hint these types.
This should fix linter errors.

Fixes Typescript errors referencing the SetOptions auth flags.

---

CHANGELOG.md
karma-sauce.conf.js

Updates the following minimum compatibilities to prevent build errors:
- The platform has been bumped to Windows 8.1, since Windows 7 is [EOL](https://www.microsoft.com/en-ww/microsoft-365/windows/end-of-windows-7-support).
- Firefox and Chrome have been bumped to versions 44 and 49, respectively, which are the [minimum versions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#browser_compatibility) that support the `let` identifier.
As you can see, the builds finally pass.

Update minimum versions in Karma-Sauce for JavaScript compatibility.

---

CHANGELOG.md
CONTRIBUTING.md
package.json

- Updates the version (minor bump because no breaking changes)
- Includes all of the CHANGELOG entries and orders them sanely
- Fixes minor typo in the CONTRIBUTING `git` command

Release v5.2.0

---

README.md

Add an npm install and missing env var setting to the xdr generation instructions.
I needed to add them to get the process to work.

Fix XDR gen instructions

---

README.md

Add instructions to prettier the xdr ts file after generating.
@Shaptic pointed out this step is required after generating, but looks like it is missing from the instructions.

Prettier xdr ts file after generating

---

src/strkey.js
test/unit/transaction_builder_test.js

A regression was introduced in 8.1.1 where raw muxed accounts were interpreted as M-addresses by `StrKey.encodeEd25519PublicKey` as a convenience, but this behavior is incorrect.
This closes stellar/js-stellar-sdk#646.

Stop trying to guess if ed25519 keys are actually med25519 keys.

---

CHANGELOG.md
src/account.js
src/fee_bump_transaction.js
src/keypair.js
src/operations/payment.js
src/transaction_builder.js
test/unit/muxed_account_test.js
test/unit/transaction_builder_test.js
types/index.d.ts
types/test.ts

To avoid a breaking change, I've introduced a way to set the source of a fee-bump transaction via account strings (in both `G...` and `M...` form). To enable proper muxed accounts, you pass `withMuxing: true` as the last parameter of `TransactionBuilder.buildFeeBumpTransaction()` just like everywhere else to explicitly opt-in. Namely,
```js
const feeTx = StellarBase.TransactionBuilder.buildFeeBumpTransaction(
feeSourceMAddress,
bumpedFee,
innerTx,
networkPassphrase,
true // optionally parses the source as a true muxed address
);
```

Add non-breaking muxed account support to fee-bump transactions.

---

CHANGELOG.md
package.json

This release completes support for muxed accounts by allowing them as fee-bump sources in `TransactionBuilder.buildFeeBumpTransaction()`.

Release v5.3.0

---

CHANGELOG.md
src/account.js
src/operations/account_merge.js
src/operations/path_payment_strict_receive.js
src/operations/path_payment_strict_send.js
src/operations/payment.js
src/util/decode_encode_muxed_account.js
test/unit/muxed_account_test.js
test/unit/operation_test.js
test/unit/strkey_test.js

**TL;DR:** Building operations with both muxed and unmuxed properties is broken without this PR.
Currently, if you called
```js
decodeAddressToMuxedAccount("G...", true)
```
you would get a `xdr.MuxedAccount(pubkey=G..., ID=0)` object (where the `G...` is the XDR-encoded public key bytes not the string, to be clear) in return. In other words, we always force G... to be fully-muxed w/ ID=0 if you opt-in to muxing. 
This behavior is broken for two reasons:
- it isn't faithful to user's expectations, and, more importantly 
- it doesn't work when you mix muxed and unmuxed parameters in operations.
For example, if you create a payment operation with a muxed destination and an unmuxed source account, it will result in XDR containing a muxed source account with an ID of zero, because you must …

Stops G-addresses from being forcefully turned into fully-muxed objects.

---

yarn.lock

This should resolve the [dependabot vulnerabilities](https://github.com/stellar/js-stellar-base/security/dependabot) related to `xmlhttprequest-ssl`, which wasn't auto-updated because of dependency chain incompatibilities.

Upgrade indirect dependency to resolve tangential security vulnerabilities.

---

CHANGELOG.md
package.json
yarn.lock

This upgrades the following libraries:
- y18n from 3.2.1 to 3.2.2 
- lodash from 4.17.11 to 4.17.21
- jsdoc from 3.5.5 to 3.6.7 (as a compatibility upgrade for `underscore`)

Upgrades various dependencies to silence dependabot.

---

yarn.lock

Everything should just resolve to 4.17.21, per [dependabot](https://github.com/stellar/js-stellar-base/security/dependabot/yarn.lock/lodash/open).

Simplify & update the lodash dependency chain

---

CHANGELOG.md
package.json

This release involves dependency updates for security purposes. 
It should be low impact, but refer to the PRs linked in the CHANGELOG for details.

Release v5.3.2

---

CHANGELOG.md
CONTRIBUTING.md
package.json
types/index.d.ts
types/test.ts

This allows all operations to set a muxed source account, as required by [CAP-27](https://stellar.org/protocol/cap-27).
While JavaScript consumers of this library are unaffected, as passing extra parameters to functions is always allowed, Typescript libraries will not compile when passing `withMuxing: true` to any operation.

Add a `withMuxing` parameter to all operation options in Typescript.

---

.github/workflows/gh_pages.yml

Whelp, that broke fast ... (see [build](https://github.com/stellar/js-stellar-base/actions/runs/1230815646)) :laughing: 
A misinterpretation of [the docs](https://github.com/actions/checkout#push-a-commit-using-the-built-in-token) on my part: The `uses` and `run` steps should be separate, and the former is already part of the first build step.

Fix logical errors in the GitHub Action for docgen.

---

.github/workflows/gh_pages.yml

The [run](https://github.com/stellar/js-stellar-base/runs/3592335593) had a different error (but at least it runs!):
>  Cloning into 'jsdoc'...
> Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
Perhaps using the native method ([docs](https://github.com/actions/checkout#checkout-multiple-repos-nested)) from `actions/checkout` will work better.

Try checking out the repo via the built-in action.

---

CHANGELOG.md
package.json

This is a patch version bump intended to update some vulnerable developer dependencies. These vulnerabilities have no meaningful impact on this repository.

Release v6.0.6

---

CHANGELOG.md
types/index.d.ts
types/test.ts

The following muxed account validation functions are now available from Typescript:
```typescript
namespace StrKey {
function encodeMed25519PublicKey(data: Buffer): string;
function decodeMed25519PublicKey(data: string): Buffer;
function isValidMed25519PublicKey(publicKey: string): boolean;
}
function decodeAddressToMuxedAccount(address: string, supportMuxing: boolean): xdr.MuxedAccount;
function encodeMuxedAccountToAddress(account: xdr.MuxedAccount, supportMuxing: boolean): string;
function encodeMuxedAccount(gAddress: string, id: string): xdr.MuxedAccount;
```

Expose muxed account validators to Typescript

---

src/transaction_builder.js

The `opts.fee` field will never be undefined because of the earlier conditional:
https://github.com/stellar/js-stellar-base/blob/cf7e64c8d2e7e2701c2a98c69e8df7297335dba0/src/transaction_builder.js#L108-L110
Thus, this ternary is not necessary.

Removes unnecessary base fee check

---

CHANGELOG.md
src/operations/set_trustline_flags.js
src/transaction.js
test/unit/operation_test.js
test/unit/transaction_test.js
types/index.d.ts

This change introduces a helper method 
```typescript
Transaction.getClaimableBalanceId(opIndex: number): string;
```
which lets you predetermine the hex claimable balance ID of a `createClaimableBalance` operation prior to submission to the network.
Closes part (1) of stellar/js-stellar-sdk#584.

Adds helper to predict claimable balance IDs given a transaction.

---

README.md
package.json
yarn.lock

This supercedes #497 and should close #496.

Upgrade cryptography dependencies (`sodium-native`, `tweetnacl`)

---

CHANGELOG.md
src/keypair.js
src/strkey.js
test/unit/keypair_test.js
test/unit/strkey_test.js
types/index.d.ts
types/test.ts

This adds support for encode signed payload signers ([CAP-40](https://stellar.org/protocol/cap-40)) to their StrKey representation ([SEP-23](https://github.com/stellar/stellar-protocol/pull/1014)):
```
+--------------------+
|   signer address   |
|                    | <------------> "PA7QYNF7SOWQ3GL..."
|      payload       |
+--------------------+
```
Closes #507.

Add support for signed payload signer keys to `StrKey`

---

CHANGELOG.md
src/asset.js
test/unit/asset_test.js

There are two changes here to the way that assets are compared:
1. In order to align better with how Stellar Core sorts assets (that is to say, in no special way besides [the default](https://github.com/xdrpp/xdrpp/blob/8756126cc734c11b75e05f174ca35a192860d0a6/xdrpp/types.h#L1019)), we rely on the actual, raw, XDR asset type (`xdr.AssetType`) value to distinguish based on type. The logic is still the same, but is much easier to understand since there are no convoluted branching string comparisons. 
2. JavaScript's [`String.prototype.localeCompare`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) function will sort strings with lowercase letters as having lower preference to those with uppercase ones (proof: …

Properly do lexographic comparison of ascii strings

---

src/keypair.js
test/unit/keypair_test.js

This wasn't caught by tests because
```js
describe('', function() {
it('', function() {
it('', function() { 
});
});
});
```
will not run the inner set of `it`s... :facepalm:

Bugfix: Signature hints should append zeroes rather than prepend them

---

CHANGELOG.md
types/index.d.ts

Encodes the correct field name in the `RevokeLiquidityPoolSponsorship` type

---

test/unit/transaction_test.js

Instead of just checking the returned `Transaction` abstraction, the tests now additionally check that the final, built XDR (i.e. the `xdr.TransactionEnvelope`) also contains the right preconditions within it.

Add round-trip XDR tests for transaction preconditions

---

types/index.d.ts
types/test.ts

We need to expose everything (new `SignerKey` helpers and new tx preconditions) in TypeScript, otherwise it won't be usable.

Add TypeScript definitions for Protocol 19

---

src/operation.js
src/operations/set_options.js
test/unit/operation_test.js
types/index.d.ts

Add support of CAP40 ed25519SignedPayload signer for SetOptionOp

---

.github/workflows/npm_publish.yml

This should specify the `--tag soroban` tag when publishing to [npm](https://www.npmjs.com/package/stellar-base), meaning you will be able to install `stellar-base@soroban`. The latest / untagged version will still only be published on [releases](https://github.com/stellar/js-stellar-base/releases).
(Note that I haven't done this in GHA before, but based on [this](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#defining-inputs-for-manually-triggered-workflows) and [this](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#example-using-event-type), it should work.)

Publish to `stellar-base@soroban` on merges to `soroban` branch.

---

CHANGELOG.md
src/asset.js

Coalesce all xLM, Xlm, etc. => 'XLM' native asset code

---

package.json
src/contract.js
test/unit/contract_test.js

The minimal footprint any call can have is the contract code being invoked. So there's no reason not to always include it.

Default to include the contract code footprint, as that is always needed

---

package.json
src/contract.js
src/operation.js
test/unit/contract_test.js

- Missed an instance of the old `.parameters()` field
- Also, fixing a bug introduced in https://github.com/stellar/js-stellar-base/pull/557

New soroban xdr updates

---

package.json
src/address.js
src/index.js
src/strkey.js
test/unit/address_test.js
test/unit/strkey_test.js
types/index.d.ts

Two things here:
- There's a new strkey type, for `C...` keys for contracts. This adds strkey parsing/serialization for those.
- When updating soroban-example-dapp, I found building ScAddresses to be a faff. Added an `Address` class to make that easier.
- I considered having two classes (`AccountAddress`, and `ContractAddress`), but didn't see the point for now.
- You would use this via: `new Address("C..34").toScVal().toXDR("base64")`, or `.toScAddress()` if that is what you wanted.

Add strkey parsing for contracts, and Address helper for building ScAddresses

---

src/fee_bump_transaction.js
src/transaction_base.js
test/unit/transaction_test.js
types/index.d.ts

I spent a while debugging this, and an error here would have helped me.
For some reason this test says that `[].some()` doesn't exist, though.. cc @Shaptic ?

Throw error if you try to sign transactions that need contract signatures.

---

package.json
src/generated/curr_generated.js
src/generated/next_generated.js
types/curr.d.ts
types/next.d.ts
xdr/curr/Stellar-overlay.x
xdr/next/Stellar-contract-spec.x
xdr/next/Stellar-contract.x
xdr/next/Stellar-ledger-entries.x
xdr/next/Stellar-ledger.x
xdr/next/Stellar-overlay.x
xdr/next/Stellar-transaction.x
xdr/next/Stellar-types.x

aka I just ran `make reset-xdr` and added the `Operation` workaround

Update generated XDR to latest version.

---

CHANGELOG.md
package.json
types/curr.d.ts
types/next.d.ts

`Operation` refers to the high-level operation, when it should be `xdr.Operation` (or, alternatively, `Operation2`, but that's uglier).

Add fully-qualified `Operation` type to XDR type definitions.

---

.github/workflows/gh_pages.yml
.github/workflows/npm_publish.yml
.github/workflows/tests.yml
CHANGELOG.md
config/karma.conf.js
config/webpack.config.browser.js
package.json
src/generated/curr_generated.js
src/generated/next_generated.js
src/util/decode_encode_muxed_account.js
test/unit/address_test.js
test/unit/contract_test.js
test/unit/strkey_test.js
test/unit/transaction_test.js
types/curr.d.ts
types/next.d.ts
xdr/curr/Stellar-overlay.x
xdr/next/Stellar-contract.x
xdr/next/Stellar-ledger-entries.x
xdr/next/Stellar-ledger.x
yarn.lock

Merge released upstream changes ([v9.0.0-beta.0](https://github.com/stellar/js-stellar-base/releases/tag/v9.0.0-beta.0)) into the Soroban branch and drop a new release (called `v9.0.0-soroban.0`). Steps taken:
- `git merge master`: resolve conflicts except XDR stuff :
- `make reset-xdr`: grab and generate latest XDR 
- `git checkout v9.0.0-beta.0 -- types/{curr,next}.d.ts`: add manual `Operation` etc. fixes back in
- modify `next_generated.js` to resolve the xdrgen bugs around using constants in arrays (see e.g. stellar/xdrgen#152), for example 
```js
xdr.varOpaque(SCVAL_LIMIT)
// into
xdr.varOpaque(xdr.lookup("SCVAL_LIMIT"))
```
- this was done for `SCVAL_LIMIT`, `SCSYMBOL_LIMIT`, and `SC_SPEC_DOC_LIMIT`
- (this isn't done in `master` since `next.d.ts` isn't used, but it probably should …

Merge upstream into `soroban` branch and tag a new version.

---

.github/workflows/npm_publish.yml
.github/workflows/tests.yml
CHANGELOG.md
package.json
yarn.lock

See the [release notes](https://github.com/stellar/js-xdr/releases/tag/v2.0.0) for why.

Upgrades dependencies to their latest versions (incl. `js-xdr@v2.0.0`).

---

CHANGELOG.md
src/asset.js
test/unit/asset_test.js

Fixes https://github.com/stellar/js-stellar-base/issues/593
Based on https://github.com/stellar/js-stellar-base/pull/605, but because what we want is ascii byte comparison. We can use `Buffer.compare` to do that for us.

Fix asset code sorting with mixed cases

---

src/operations/invoke_host_function.js
src/transaction_builder.js
test/unit/operation_test.js
test/unit/transaction_builder_test.js
types/index.d.ts

while developing soroban-client to support new rpc simulation on [js-soroban-client#77](https://github.com/stellar/js-soroban-client/pull/77), needed a way to stuff the new SorobanTransactionData from simulation into the transaction during TxBuilder for easier client usage.

added transaction ext as tx builder param

---

src/operation.js

Adds missing jsdoc for `Operation.isValidAmount`.

---

src/contract.js
test/unit/contract_test.js
types/index.d.ts

Will fix the system-tests breakage at: https://github.com/stellar/soroban-tools/actions/runs/5121655313/jobs/9209699526?pr=668
Now you can do:
```
// constructor will auto-detect c-strkey, or hex string
let c = new Contract("C...1234");
// default is changed to strkey output
console.log(c.contractId());
// C...1234
// old style hex output is via the new format parameter
console.log(c.contractId('hex'));
// abcd1234
```

Add Contract support for strkey-style contract IDs

---

src/contract.js
test/unit/contract_test.js

Should help with https://github.com/stellar/js-soroban-client/pull/97

Add Contract.address() method

---

package.json
types/index.d.ts

Missed a couple typescript definition updates in v9.0.0-soroban.2

Release v9.0.0-soroban.3

---

types/index.d.ts

Add missing `StrKey` helpers to TypeScript definitions

---

.github/workflows/npm_publish.yml
CHANGELOG.md
package.json
yarn.lock

This is a large update and the following changelog incorporates ALL changes across the `beta.N` versions of this upgrade (i.e. since v8.2.2).
-------------
This version is marked by a major version bump because of the significant upgrades to underlying dependencies. While there should be no noticeable API changes from a downstream perspective, there may be breaking changes in the way that this library is bundled.
The browser bundle size has decreased **significantly**:
* `stellar-base.min.js` is **340 KiB**, down from **1.2 MiB** previously.
* the new, unminified `stellar-base.js` is **895 KiB**.
- The build system has been completely overhauled to support Webpack 5 ([#584](https://github.com/stellar/js-stellar-base/pull/584), [#585](https://github.com/stellar/js-stellar-base/pull/585)). …

Prepare `v9.0.0` for promotion and release.

---

package.json
src/operations/invoke_host_function.js
src/transaction_base.js
test/unit/transaction_test.js

- Many XDR structures have changed, please refer to the `types/next.d.ts` diff for details ([#633](https://github.com/stellar/js-stellar-base/pull/633)).
- We have returned to the world in which **one** transaction contains **one** operation which contains **one** host function invocation. This means `Operation.invokeHostFunctions` is gone and `Operation.invokeHostFunction` has changed to accept `{ func, auth }`, where `func` is the correct `xdr.HostFunction` and `auth` is a list of `xdr.SorobanAuthorizationEntry` items that outline the authorization tree for the call stack ([#633](https://github.com/stellar/js-stellar-base/pull/633)). Better abstractions for creating an `xdr.HostFunction` are forthcoming, though you can still refer to `Contract.call()` for help.
- A new abstraction for …

Release `v10.0.0-soroban.0`

---

package.json
types/index.d.ts

This was overlooked in #633 and prevents `soroban-client` from building invocations correctly without `as unknown` hacks.

Fix TypeScript definition for `Operation.invokeHostFunction` options

---

package.json
src/contract.js
test/unit/contract_test.js

For preview 10 we need to pass the contract id as an ScAddress, not an ScBytes.

Fix Preview 10 contract invoke & Release `v10.0.0-soroban.3`

---

src/scval.js
test/unit/scval_test.js

The conversion behavior of strings and symbols has changed:
* before: `scvString` -> `Uint8Array` OR `string`
* after: `scvString` -> decoded as UTF-8, returns `string`
* before: `scvSymbol` -> `Uint8Array` OR `string`
* after: `scvString` -> always decoded as an ascii `string`
The following is true:
* symbols MUST be strings, as their input is enforced to be `[a-zA-Z0-9_]+`
* strings are "bytes with a hint of being text," so we should respect that 
Previously, users were seeing byte arrays when they expected strings, so this rectifies that unintuitive behavior.
UTF-8 encoding is assumed for `scvString`s (because it's ascii-compatible), but there's not really a compelling reason to assume anything else (utf8 is assumed throughout most of the toolchain, and if you want something different …

Make opinionated judgements about string/symbol decoding

---

package.json
yarn.lock

This includes #645 and upgrades applicable `devDependencies` to minor versions.

Prepare `soroban.4` tag for release

---

src/numbers/index.js
src/numbers/sc_int.js
src/numbers/xdr_large_int.js
src/scval.js

Examples aren't rendered correctly with Markdown syntax, see e.g. https://stellar.github.io/js-soroban-client/global.html#scValToBigInt. We also weren't getting certain cross-references (e.g. to `XdrLargeInt`) because the ref wasn't documented. This should fix those issues.

Fix various jsdoc rendering and cross-reference issues.

---

config/webpack.config.browser.js
package.json
yarn.lock

* crc was inlined as part of #621 
* crypto-browserify isn't used (we use sodium/tweet)

Clean up unnecessary dependency entries

---

src/contract.js
test/unit/contract_test.js
types/index.d.ts

feat!: drop support for hex contract IDs

---

src/auth.js
src/index.js
src/numbers/xdr_large_int.js
test/unit/auth_test.js
test/unit/contract_test.js
types/index.d.ts

Replaces #632 in an attempt to tackle #575. This adds three helpers (see the jsdocs for details):
```typescript
function authorizeInvocation(
signer: Keypair,
networkPassphrase: string,
validUntil: number,
invocation: xdr.SorobanAuthorizedInvocation
): xdr.SorobanAuthorizationEntry;
function buildAuthEnvelope(
networkPassphrase: string,
validUntil: number,
invocation: xdr.SorobanAuthorizedInvocation
): xdr.HashIdPreimage;
function buildAuthEntry(
envelope: xdr.HashIdPreimage,
signature: Buffer | Uint8Array,
publicKey: string
): xdr.SorobanAuthorizationEntry;
```

Add helpers method to build authorization entries.

---

Makefile
src/auth.js
src/contract.js
src/generated/curr_generated.js
src/generated/next_generated.js
src/scval.js
src/sorobandata_builder.js
test/unit/auth_test.js
test/unit/contract_test.js
test/unit/operation_test.js
test/unit/sorobandata_builder_test.js
test/unit/transaction_builder_test.js
types/curr.d.ts
types/next.d.ts
xdr/next/Stellar-contract-config-setting.x
xdr/next/Stellar-contract.x
xdr/next/Stellar-ledger.x
xdr/next/Stellar-transaction.x

Upgrades the Soroban XDR to the latest version.

---

src/transaction_builder.js
test/unit/transaction_builder_test.js
types/index.d.ts

This suggestion comes from @sreuland after #656 to clear out operations from a builder to allow them to be built separately. This is particularly key for Soroban operations in configuring auth.

Add ability to clear out operations from the transaction builder

---

src/numbers/sc_int.js
types/index.d.ts

* Adds a missing method to `XdrLargeInt`s TypeScript definition
* Removes `ScInt` from constructor (it isn't handled at all)

Fixes missing / incorrect TypeScript descriptions.

---

src/contract.js
test/unit/contract_test.js
types/index.d.ts

Add the correct `xdr.LedgerKeyContractCode` instance to the contract's default access footprint.

Expand contract footprint with contract code ledger key.

---

Makefile
config/prettier.config.js
src/generated/next_generated.js
types/next.d.ts

This incorporates https://github.com/stellar/xdrgen/pull/165.

Regenerate XDR with new generator version

---

src/sorobandata_builder.js
test/unit/sorobandata_builder_test.js
types/index.d.ts

This makes it easier to build the data structure from an existing footprint.

Add ability to modify and retrieve the resource footprint

---

CHANGELOG.md
src/operations/create_account.js
src/operations/liquidity_pool_deposit.js
src/operations/liquidity_pool_withdraw.js
test/unit/operation_test.js

Closes https://github.com/stellar/js-stellar-base/issues/528.

Fixes error messages for required amount parameters

---

src/asset.js
test/unit/asset_test.js
types/index.d.ts

This just needs a few more test cases before it's ready to merge, cc @orbitlens.

Add `Asset.contractId()` helper to predict contract IDs

---

src/sorobandata_builder.js
test/unit/sorobandata_builder_test.js
types/index.d.ts

This does two things:
* **change:** the default structure will kick in on **any** "falsy" parameter, now (before, it considered string/buffer first, but this meant empty strings, e.g. from Soroban RPC, were interpreted incorrectly)
* **add:** `getFootprint()` to easily get both read-only and read-write pieces

Improves `SorobanDataBuilder` construction and adds a getter

---

package.json
yarn.lock

**Notice:** This is the final release that will be compatible with Preview 10.
* Adds a way to represent Soroban invocation trees as JSON for easier parsing ([#669](https://github.com/stellar/js-stellar-base/pull/669)).
* Adds `SorobanDataBuilder.getFootprint()` to retrieve the underlying footprint directly ([#686](https://github.com/stellar/js-stellar-base/pull/686)).
* The `SorobanDataBuilder` constructor now properly handles "falsy" values (like empty strings) to create an empty structure ([#686](https://github.com/stellar/js-stellar-base/pull/686)).
* Various dependencies have been upgraded to their latest versions ([#685](https://github.com/stellar/js-stellar-base/pull/685)).

Prepare `v10.0.0-soroban.8` for release.

---

CHANGELOG.md
types/index.d.ts

This bug prevented all non-integer types from being passed via `{ type: '...' }` (such as `'symbol'` or `'address'`) when used from TypeScript without casting `as any`.

Fix type definition of optional parameter

---

CHANGELOG.md
package.json
src/contract.js
test/unit/contract_test.js

The type of `InvokeContractArgs.functionName` is supposed to be a `string` now, not an `ScSymbol` like before.
This **should** have been caught by testing but they were being skipped with `xit` by mistake :facepalm:

Correctly build operations via `Contract.call()`

---

CHANGELOG.md

Includes a critical bugfix, see changelog.

Prepare v10.0.0-beta.1 for release

---

CHANGELOG.md
types/index.d.ts

Closes https://github.com/stellar/js-stellar-base/issues/695.

Fix type definition for `Memo.hash` to allow buffers

---

src/auth.js

For some reason, !== on the object does not work in some envs. 
Note that it works fine in the unit tests.
This is a faster check, anyway.
Reported by @tyvdh on Discord [here](https://discord.com/channels/897514728459468821/1138959805218836510/1161061470289789038).

Fixes a type comparison bug in authorization helpers.

---

CHANGELOG.md
src/contract.js
test/unit/contract_test.js
test/unit/sorobandata_builder_test.js
types/index.d.ts

Context: The work done in was https://github.com/stellar/js-stellar-base/pull/662 simply incorrect: the hash in the code key should correspond to the hash of the WASM code, not the contract ID.

Drop incorrect key entry for contract footprint

---

CHANGELOG.md
package.json
src/transaction_builder.js

- You can now correctly clone transactions (`TransactionBuilder.cloneFrom`) with large sequence numbers.

Release beta.4 with a sequence number bugfix.

---

types/index.d.ts

It's supposed to be `string` not `Address`

correct the return type to 'string'

---

.github/workflows/npm_publish.yml
package.json
src/generated/curr_generated.js
src/generated/next_generated.js
src/index.js
src/memo.js
src/numbers/int128.js
src/numbers/int256.js
src/numbers/uint128.js
src/numbers/uint256.js
src/numbers/xdr_large_int.js
src/operation.js
src/operations/bump_sequence.js
src/operations/change_trust.js
src/operations/manage_buy_offer.js
src/operations/manage_sell_offer.js
src/soroban.js
src/transaction.js
src/transaction_builder.js
test/unit/i256_test.js
test/unit/soroban_test.js
test/unit/transaction_test.js
yarn.lock

Notice that this is targeting the `stable` branch: we will only include this rename as part of the stable package release.
See stellar/js-xdr#111, stellar/js-xdr#112, and stellar/js-xdr#113 for what was needed in that package to accomplish this.
This also moves the code to use `@stellar/js-xdr` instead of `js-xdr`.
Related: stellar/js-stellar-sdk#851.

Republish package under @stellar/ scope

---

types/index.d.ts

This commit addressed the issue reported in https://github.com/stellar/js-stellar-base/issues/717
When using js-stellar-base and js-stellar-sdk to manage assets, the method `contractId()` always returns an error.
By looking at the source code, we can see the method expects an argument that is not present in the exported type.
- **Method**:
https://github.com/stellar/js-stellar-base/blob/cf370f4e627e2b0e296ceceaebd0164dede396bd/src/asset.js#L111
- **Exported type**:
https://github.com/stellar/js-stellar-base/blob/cf370f4e627e2b0e296ceceaebd0164dede396bd/types/index.d.ts#L82C3-L82C13
Forcing typescript to ignore the error and providing the network passphrase as an argument overcomes the issue. It is necessary to update the type to reflect the need for an argument.

Fix asset class contractId missing argument

---

src/events.js
test/unit/events_test.js

Both the documentation and the TypeScript definitions outline it as being omitted when the field is not present in the event (in case of system events), so this is a bugfix rather than a breaking change.

Actually omit the 'contractId' field from humanized events when it's empty

---

CHANGELOG.md
src/account.js
src/index.js
src/memo.js
src/operation.js
src/operations/bump_sequence.js
src/operations/change_trust.js
src/transaction_builder.js
src/util/bignumber.js
src/util/continued_fraction.js
test/unit/util/bignumber_test.js

Remove setting `BigNumber.DEBUG` to `true` to avoid global impact.

---

.github/workflows/npm_publish.yml
CHANGELOG.md
package.json
yarn.lock

**Note:** This version is (still) compatible with Protocol 20. Most people should be unaffected by the technically-breaking changes and can treat this more like a v10.0.3 patch release (see changelog).

Release v11.0.0

---

package.json

Reduces bundle size by 95%.
Before, as measured by [bundle-phobia-cli](https://github.com/AdrieanKhisbe/bundle-phobia-cli):
```
$ bundle-phobia -p ./package.json
ℹ @stellar/js-xdr (3.1.0) has 0 dependencies for a weight of 43.86KB (12.32KB gzipped)
ℹ base32.js (0.1.0) has 0 dependencies for a weight of 2.24KB (877B gzipped)
ℹ bignumber.js (9.1.2) has 0 dependencies for a weight of 18.19KB (8.15KB gzipped)
ℹ buffer (6.0.3) has 2 dependencies for a weight of 26.83KB (7.95KB gzipped)
ℹ sha.js (2.4.11) has 2 dependencies for a weight of 12.04KB (4.18KB gzipped)
ℹ tweetnacl (1.0.3) has 0 dependencies for a weight of 31.51KB (10.46KB gzipped)
ℹ typescript (5.3.3) has 0 dependencies for a weight of 3.15MB (890.61KB gzipped)
ℹ total (7 packages) has 4 dependencies for a weight of 3.28MB (934.53KB …
```

build: move typescript to devDependencies

---

config/buffer.js
config/webpack.config.browser.js
package.json
yarn.lock

We need to wait for the new version of js-xdr to be released first.

Add compatibility with pre-ES2016 environments (like some React Native JS compilers) by adding a custom `Buffer.subarray` polyfill

---

CHANGELOG.md
Makefile
src/generated/curr_generated.js
src/generated/next_generated.js
types/curr.d.ts
types/next.d.ts
xdr/curr/Stellar-contract-config-setting.x
xdr/curr/Stellar-ledger-entries.x
xdr/curr/Stellar-ledger.x
xdr/next/Stellar-contract-config-setting.x
xdr/next/Stellar-ledger-entries.x
xdr/next/Stellar-ledger.x

This updates the XDR to stellar/stellar-xdr@1a04392432dacc0092caaeae22a600ea1af3c6a5.

Upgrade XDR to Protocol 21

---

src/strkey.js

Hi team, we are running stellar code in a [sandbox](https://www.npmjs.com/package/vm2), and in our production env we are prohibit to inject any additional modules into this sandbox. 
In following code you can see we try to get `.publicKey()` from a keypair, this will throw an error 
`Failed to execute script. TypeError [ERR_INVALID_ARG_TYPE]: The "list[1]" argument must be an instance of Buffer or Uint8Array. Received an instance of Object`, this is due to in sandbox env could not identify Unit8Array so it been treated as an object here. 
```js
const {NodeVM, VMScript} = require('vm2');
const {Keypair} = require('@stellar/stellar-base')
const vm = new NodeVM({
require: {
builtin: ['crypto'],
external: true,
context: 'sandbox',
resolve: (moduleName) => {
return require.resolve(moduleName, …
```

Add Buffer.from checkSum to fix buffer concat could fail

---

src/operations/extend_footprint_ttl.js
src/operations/restore_footprint.js
test/unit/operations/extend_restore_test.js

Extend TTL doc was incorrect, and restore doc lacked some important details.

Updated the docs for extend/restore footprint ops.

---

CHANGELOG.md
src/scval.js
test/unit/scval_test.js

Errors were updated, but converting them to native objects wasn't. Errors are now converted to the following format:
```typescript
interface Error {
type: "contract" | "system";
code: number;
value?: string; // only present for type === 'system'
}
```

Fix handling `ScError` types in `scValToNative`

---

CHANGELOG.md
src/asset.js
test/unit/soroban_test.js

This increases cross-compatibility across different instances of `stellar-base` by comparing integers rather than objects (which will be `!=` given two different `base`s).

Compare assets by integer rather than by object

---

CHANGELOG.md
src/scval.js
test/unit/scval_test.js

Closes stellar/js-stellar-sdk#996 and stellar/js-stellar-sdk#966.
Note that test changes just involve changing the order of the map fields to be sorted accordingly in the "expected output" portion of the test.
Also, the diff is simpler if you [turn whitespace off](https://github.com/stellar/js-stellar-base/pull/759/files?diff=unified&w=1).

Automatically sort maps to match Soroban environment expectations

---

src/transaction_builder.js
test/unit/transaction_builder_test.js

- Added two methods: `addOperationAtIndex` and `clearOperationAtIndex` in the `TransactionBuilder` class 
I wanted to add them because I was trying to change the amount of one operations after cloning and realized it would that much easier if I could just clear an operation at a specified index and then add it add the updated operation at the same index again.

added clearing and adding operations at a specified index

---

CHANGELOG.md
src/scval.js
src/transaction_builder.js
test/unit/scval_test.js
test/unit/transaction_builder_test.js

Previously, `i32` and `u32` could not automatically come from string values when using `nativeToScVal`. Namely, `nativeToScVal("4", { type: "i32" })` was explicitly forbidden. This was my design: the rationale was that if it's a 32-bit integer, it should be passed as a `Number`. 
However, this logic does not hold true for maps, because in JavaScript, all map keys are strings. Therefore, creating an `ScVal` representing an integer-to-integer map is impossible via `nativeToScVal`, e.g., a function signature like this one:
```rust
fn spin(env: Env, pairs: Map<u32, u64>) -> boolean;
```
cannot be executed by 
```js
nativeToScVal(
{ 1234: 5678 }, 
{ 
type: { 
"1234": [ "u32, "u64" ],
"5678": [ "u32, "u64" ],
}
);
```
because `1234` would be interpreted as a string, and thus could not be …

Add support for `nativeToScVal` to convert strings to all number sizes.

---

.github/workflows/format.yml
src/operation.js
src/operations/index.js
src/operations/invoke_host_function.js
test/unit/operations/invoke_host_function_test.js
types/index.d.ts

Upgrade the `createCustomContract` abstraction to accept a new, optional parameter:
```diff
class Operation {
// ...
createCustomContract(
address: Address,
wasmHash: Buffer | Uint8Array,
+   constructorArgs?: xdr.ScVal[],
salt?: Buffer | Uint8Array,
...
```
and upgrade the internals to use the `CreateContractV2` host function.
This closes #768.

Support constructors in contract creation via `Operation.createCustomContract`

---

.github/workflows/npm_publish.yml
CHANGELOG.md
package.json

In order to keep `master` clean for bugfixes during the transition period, we should release from the Protocol 22 branch which has a well-defined set of already-approved and merged PRs (see lucky https://github.com/stellar/js-stellar-base/pull/777).
This PR tags off the version, publishes under the `beta` tag on NPM, and updates the changelog.
Note that this is tagged as a `beta` instead of an `rc` so that we can properly handle any anticipated changes to core that occur throughout the release process (e.g. patch fixes after `v22.0.0` that require XDR structure or behavior changes), as was the case with Protocol 20.

Prepare v13.0.0-beta.1 (Protocol 22) for release.

---

CHANGELOG.md
package.json
src/invocation.js
test/unit/invocation_test.js

This also incorporates a patch release to get this out as quickly as possible.

Add support for `buildInvocationTree` to parse V2 of creation calls

---

src/scval.js
src/xdr.js
test/unit/scval_test.js
types/curr.d.ts

Injects an `scvMapSorted` constructor into the `xdr` module so that people can created maps with sorted entries from raw `ScMapEntry` instances.
Closes stellar/js-stellar-sdk#1131.

Add an `xdr.scvMapSorted` constructor to automagically sort map `ScVal`s.

---

CHANGELOG.md
src/auth.js
test/unit/auth_test.js
types/index.d.ts

Closes https://github.com/stellar/js-stellar-base/issues/780 per discussion in https://github.com/stellar/js-stellar-base/pull/772#discussion_r1764307846: `authorizeEntry` can now take a callback that returns an object specifying the signer of the signature so that it isn't implied that it's the address in the entry. Namely, it can return
```typescript
interface SigningCallbackResult {
signature: Buffer | Uint8Array;
publicKey: string;
}
```

Extend `SigningCallback` form to allow returning an object

---

CHANGELOG.md
types/index.d.ts

This function does not exist in [`MuxedAccount`](https://github.com/stellar/js-stellar-base/blob/087e2d651a59b5cbed01386b4b8c45862d358259/src/muxed_account.js#L48), so we should remove it. Or should we add this function as an alias for [`extractBaseAddress`](https://github.com/stellar/js-stellar-base/blob/087e2d651a59b5cbed01386b4b8c45862d358259/src/muxed_account.js#L74)?

Remove `MuxedAccount.parseBaseAddress` from TypeScript definitions.

---

src/strkey.js
test/unit/strkey_test.js
types/index.d.ts

Closes https://github.com/stellar/js-stellar-base/issues/793 by lining the SDK up with the latest changes (https://github.com/stellar/stellar-protocol/pull/1646) to [SEP-23](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0023.md).

Add strkey support for liquidity pools and claimable balances

---

package.json
src/index.js
src/keypair.js
src/signing.js
test/unit/signing_test.js
yarn.lock

Having two methods is janky, sodium-native doesn't build on some systems, and [@noble/curves](https://github.com/paulmillr/noble-curves) is an [audited](https://github.com/paulmillr/noble-curves?tab=readme-ov-file#security), modern, high-performance library that achieves the same goals.

Migrate cryptographic libraries to use modern @noble/curves.

---

src/address.js
src/operations/invoke_host_function.js
src/strkey.js
test/unit/address_test.js
test/unit/operations/invoke_host_function_test.js

* LPs, CBs, and muxed accounts now can be converted:
- from strkey -> Address
- Address -> ScVal
- Address -> ScAddress
- ScVal -> Address

Add support for encoding `Address` to/from new `StrKey`s

---

docs/reference/base-examples.md
docs/reference/building-transactions.md
src/keypair.js
src/numbers/xdr_large_int.js
src/operations/invoke_host_function.js
src/scval.js
test/unit/scval_test.js

Previously, you could only specify a single type or use defaults:
```js
nativeToScVal([1, 2, 3], { type: 'i128' }); // Vec<I128>
nativeToScVal([1, "2", 3], { type: 'i128' }); // error
nativeToScVal([1, "2", 3]); // Vec<u32, string, u32>
```
but now you can specify types for each element in the array
```js
nativeToScVal([1, "2", 3], { type: ['i128', 'string', 'i128'] }); // Vec<I128, String, I128>
```
This is super helpful because contracts are just `Vec<Val>` so they can be anything and unnamed enums also require this format.

Allow specifying mixed types for vectors in `nativeToScVal`

---

CHANGELOG.md
src/address.js
test/unit/address_test.js

The encoding of muxed accounts in XDR is different from that in StrKey; XDR uses an 8-byte ID + 32-byte key, while StrKey uses a 32-byte key + 8-byte ID.

Fixes muxed account handling in `Address` class
